### ISSUE TITLE
Ball Ball了1.54还能见吗 /(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by takaqiao** [VM-Chinese-translate-group/Roguelike-Adventures-and-Dungeons#133]
RT

**Comment by nageih** [comment]
很难了，组内目前有很多别的计划，有机会会更新的

**Comment by Wulian233** [comment]
无期

**Comment by Wulian233** [comment]
@takaqiao Progressing
https://github.com/VM-Chinese-translate-group/Roguelike-Adventures-and-Dungeons/issues/134
